feat(user): Auth and user endpoints complete
ucladevx/BPool pull request #5
Opened 2018-04-09 01:56 UTC by codyleyhan

# Description
- Adjusts google oAuth to just accept and verify token now
    - once verified issues a JWT access token
- Fixes the users spelling error #2 
- Adds user endpoints for
1. /Login
2. /users/ with pagination
3. /users/:id
4. /users/@me
- adds in user claims 
- adds in a user auth middleware
- updates the logger to reduce code duplication

# Steps to reproduce
- Ensure that you have a fresh DB
- Run the server
- Use the front-end to get your oauth token
- post this token to /api/v1/login (now logged in and will return JWT access token)
- can now hit /users/@me to see your user info
- For /users/ adjust in DB to give yourself auth_level = 1 (admin level) 
- can also hit /users/:id unauthenticated

# Tested
**Nothing tested yet**

# Approved
- [ ] Jahan
- [ ] Luke

2018-04-09 20:09 UTC, epicchewy requested changes
minor changes for clarity

2018-04-09 20:09 UTC, epicchewy commented on adapters/http/user.go
> +	c.GET("/users/", u.list, auth.NewAuthMiddleware(services.UserLevel, u.logger))
extra backslash at end?

2018-04-09 20:09 UTC, epicchewy commented on services/user.go
> +	user, err = u.store.GetByEmail(googleUser.Email)
assign user here?

2018-04-09 20:09 UTC, epicchewy commented on utils/auth/google_authorizer_test.go
> +	if !reflect.DeepEqual(expectedUser, *user) {
move to asserts eventually?

2018-04-09 20:09 UTC, epicchewy commented on services/user.go
> +	if user == nil {
leave comment about adding new user because we're using google auth for all users

2018-04-09 20:42 UTC, codyleyhan commented on adapters/http/user.go
> +	c.GET("/users/", u.list, auth.NewAuthMiddleware(services.UserLevel, u.logger))
Yeah needed

2018-04-09 22:26 UTC, codyleyhan commented
Fat 1000 line PR coming in hot

2018-04-09 22:28 UTC, epicchewy approved these changes

2018-04-09 22:28 UTC, epicchewy commented
lgtm

2018-04-10 17:15 UTC, jcherianucla approved these changes
Other than the limit, everything looks good to me

2018-04-10 19:59 UTC, merged