feat(rides): adds rides model and change set
ucladevx/BPool pull request #7
Opened 2018-04-18 03:14 UTC by codyleyhan

Start, just keeping it open so we can have conversations while it is built

2018-04-18 05:47 UTC, codyleyhan commented
Already see that the date is not working correctly, will work on that

2018-04-19 04:38 UTC, jcherianucla requested changes
Most of it looks good but I want to try and revisit:
1.) Validation - Retry govalidator or another package
2.) Updates - I like the change set, but I don't like the crazy amount of if statements. Reflection could work, but tradeoffs in performance and readability to new devs. Maybe we should look into this a little more just to be confident.

2018-04-19 04:38 UTC, jcherianucla commented on app.go
>  	userController.MountRoutes(auth)
Change to individual groups for each controller to decouple them.

2018-04-19 04:38 UTC, jcherianucla commented on models/ride.go
> +
nit: Repeated if statement for DriverID

2018-04-19 04:38 UTC, jcherianucla commented on models/ride.go
> +	}
nit: Car ID and Driver ID are capitalized but the others are not. Let's chose one or the other.

2018-04-19 04:38 UTC, jcherianucla commented on models/ride.go
> +		PricePerSeat int       `json:"price_per_seat" db:"price_per_seat"`
Prices could be floats? What if we want a price like $5.50 per seat.

2018-04-19 04:38 UTC, jcherianucla commented on models/ride.go
> +
No need for a Merge, just create a copy of the value of existing ride to newRide and update it accordingly. Removes extra dependency.

2018-04-19 04:38 UTC, jcherianucla commented on models/ride.go
> +
Same as above with regards to mergo.

2018-04-19 04:38 UTC, jcherianucla commented on stores/postgres/ride.go
> +	var ride models.Ride
Let's stick to ride := models.Ride{}

2018-04-20 06:57 UTC, jcherianucla approved these changes

2018-04-20 06:58 UTC, jcherianucla approved these changes
Looks good to me

2018-04-20 19:25 UTC, epicchewy commented
lgtm

2018-04-24 01:39 UTC, codyleyhan commented
There were some changes so @epicchewy @jcherianucla  can you take a look again

2018-04-24 06:10 UTC, jcherianucla approved these changes
Looks lit to me

2018-04-24 16:15 UTC, merged